Repository CatalysmsServerManager/7-days-to-die-server-manager, pull requests merged in 2020-11, with the labels that each got.

#431 Revamp Docker image and workflows
  .github/workflows/docker.yml
  Dockerfile
Labels: chore

#447 Upgrade Discordjs version
  Dockerfile
  api/controllers/SdtdServer/discordBot/check-if-bot-is-in-guild.js
  api/controllers/SdtdServer/discordBot/find-channel-by-id.js
  api/controllers/SdtdServer/discordBot/find-writeable-channels-in-guild.js
  api/controllers/SdtdServer/discordBot/get-server-roles.js
  api/controllers/SdtdServer/discordBot/set-chat-channel.js
  api/controllers/SdtdServer/discordBot/set-discord-guild.js
  api/controllers/SdtdServer/discordBot/set-notification-channel.js
  api/controllers/SdtdServer/discordBot/set-prefix.js
  api/controllers/User/find-guilds-managed-by-user.js
  api/helpers/meta/get-donator-status.js
  api/helpers/meta/load-system-stats-and-info.js
  api/hooks/customDiscordNotification/index.js
  api/hooks/discordBot/commands/meta/import-server.js
  api/hooks/discordBot/commands/sdtd/execCommand.js
  api/hooks/discordBot/index.js
  api/hooks/discordBot/util/createEmbed.js
  api/hooks/discordChatBridge/index.js
  package-lock.json
  package.json
  test/integration/controllers/setChatChannel.test.js
  test/unit/hooks/discordCommands/serverInfo.test.js
  test/unit/hooks/discordCommands/status.test.js
  test/unit/hooks/discordNotifications/DiscordNotification.test.js
  test/unit/hooks/discordNotifications/notifications/cronJob.test.js
  test/unit/hooks/discordNotifications/notifications/gblMaxBan.test.js
  worker/processors/discordNotification/notifications/cronJob.js
Labels: dependencies

#453 Fix issue fetching list of manageable guilds from Discord
  api/controllers/User/find-guilds-managed-by-user.js
Labels: bug

#457 Lower Sentry transaction sample rate
  api/hooks/sentry.js
Labels: chore

#456 Move custom hooks to worker process
  api/controllers/CustomHook/add-custom-hook.js
  api/controllers/CustomHook/edit-custom-hook.js
  api/controllers/CustomHook/variable/add-hook-variable.js
  api/hooks/bullboard.js
  api/hooks/customHooks/index.js
  api/hooks/sdtdLogs/LoggingObject.js
  api/models/CustomHook.js
  api/models/HookVariable.js
  package-lock.json
  package.json
  test/unit/hooks/customHook/hook.test.js
  worker/processors/hooks/enrichEventData.js
  worker/processors/hooks/index.js
  worker/worker.js
Labels: enhancement

#458 Fix issue fetching manageable discord guilds
  api/controllers/User/find-guilds-managed-by-user.js
Labels: bug

#459 Delete call to start customHooks from set active helper
  api/helpers/meta/set-server-active.js
Labels: bug

#460 Remove some references to deleted hook
  api/models/SdtdConfig.js
  worker/worker.js
Labels: bug

#461 Do not error out when user is not in a Discord guild
  api/controllers/User/find-guilds-managed-by-user.js
Labels: bug

#464 Use Sequelize for the health check
  api/controllers/etc/health.js
Labels: chore

#465 Initial performance improvements wrt slow queries
  api/helpers/meta/load-system-stats-and-info.js
  api/helpers/meta/start-usage-stats-gathering.js
  migrations/20201110094358-add-index-public-teleports.js
  migrations/20201110095817-add-index-analytics.js
Labels: chore

#466 Use raw queries for deletion of tracking data
  api/hooks/historicalInfo/objects/memUpdate.js
  test/unit/hooks/playerTracking/playerTracking.test.js
  worker/processors/playerTracking/index.js
Labels: enhancement

#467 Fixes for support ticket views
  api/controllers/SdtdTicket/server-tickets-view.js
  views/sdtdTicket/ticket.sejs
Labels: bug

#469 Control analytics enabled status with env vars
  api/hooks/historicalInfo/index.js
  config/custom.js
Labels: enhancement

#472 Add Datadog integration
  app.js
  package-lock.json
  package.json
  worker/worker.js
Labels: enhancement

#473 Keep more jobs around after completion/failing
  api/helpers/get-queue-object.js
Labels: bug

#474 Only load datadog when relevant env variables are given
  api/utils.js
  app.js
  worker/worker.js
Labels: enhancement

#477 More control over what people can add new servers to an instance
  .env.example
  api/controllers/SdtdServer/add-server.js
  test/unit/helpers/sdtd/add-server-helpers.test.js
  views/sdtdServer/addserver.sejs
Labels: enhancement

#478 Add tracing to worker jobs
  api/utils.js
  worker/worker.js
Labels: enhancement

#480 Add new super simple easy to help debug 'me' controller
  api/controllers/User/me.js
  config/routes.js
Labels: enhancement

#481 Exit early and log error when hooks processor doesnt get good data
  worker/processors/hooks/index.js
Labels: bug
