Repository CatalysmsServerManager/7-days-to-die-server-manager, pull requests merged in 2020-08, with the labels that each got.

#228 Fix the highpingcount crash
  api/hooks/highPingKick/index.js
  test/lifecycle.test.js
  test/unit/helpers/sdtd/validate-item-name.test.js
  test/unit/hooks/countryBan/countryBan.test.js
  test/unit/hooks/highPingKick/index.test.js
Labels: bug

#232 Add Sentry logo to README
  README.md
  assets/images/meta/sentry.png
Labels: chore

#231 Fix #230 - lookup breaking
  api/hooks/discordBot/commands/sdtd/lookup.js
  api/hooks/discordBot/commands/sdtd/player.js
Labels: bug

#239 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: chore

#246 Revert dotenv upgrade
  package-lock.json
  package.json
Labels: bug, dependencies

#253 Update dotenv to 8.2.0
  create_tables.js
  package-lock.json
  package.json
Labels: dependencies

#257 Don't use classToHook in highPingKick
  api/hooks/highPingKick/index.js
Labels: bug

#259 Fix highpingcount again
  api/hooks/highPingKick/index.js
  api/utils.js
Labels: bug

#272 Fix log count setting
  config/custom.js
Labels: bug

#273 Deprecate/remove Discord import/export
  api/hooks/discordBot/commands/meta/export-server.js
  api/hooks/discordBot/commands/meta/import-server.js
Labels: chore

#287 Sync Discord and CSMM roles when a user (re)connects their Discord profile
  api/controllers/AuthController.js
  api/helpers/discord/discordRequest.js
  api/helpers/discord/set-role-from-discord.js
  api/hooks/discordBot/roles/handleRoleUpdate.js
  test/lifecycle.test.js
  test/unit/helpers/discord/setRoleFromDiscord.test.js
  test/unit/hooks/discordBot/handleRoleUpdate.test.js
Labels: enhancement

#288 Only start logging hook after sails is ready
  api/hooks/sdtdLogs/index.js
Labels: enhancement

#290 Dont build docker image with sha tag
  .github/workflows/docker.yml
Labels: chore

#293 Economy modifiers set by roles are not applied to shop items
  api/controllers/Shop/listing-buy.js
  test/integration/controllers/shop.test.js
  test/unit/helpers/discord/setRoleFromDiscord.test.js
  test/unit/hooks/discordBot/handleRoleUpdate.test.js
Labels: bug

#294 Shop item validation does not support custom items with spaces
  api/controllers/Shop/listing-add.js
  api/helpers/sdtd/validate-item-name.js
  test/integration/controllers/shop.test.js
Labels: bug
