Repository CatalysmsServerManager/7-days-to-die-server-manager, pull requests merged in 2020-07, with the labels that each got.

#157 Fix `.then() only accepts functions but was passed: [object Undefined], [object Undefined]`
  api/controllers/SdtdServer/settings.js
Labels: bug

#155 Make sure we use SdtdServer.getAPIConfig when calling sdtdapi calls
  api/controllers/Player/give-item.js
  api/helpers/sdtd/validate-item-name.js
Labels: bug

#173 Install lefthook for better git hooks
  lefthook.yml
  package-lock.json
  package.json
Labels: chore

#188 GBL Notification bug
  api/hooks/countryBan/index.js
  api/hooks/discordNotifications/notifications/countrybanKick.js
  test/lifecycle.test.js
  test/unit/hooks/countryBan/countryBan.test.js
Labels: bug

#186 Add randNum variable - fixes #118
  api/helpers/sdtd/fill-custom-variables.js
  test/unit/helpers/sdtd/fill-custom-variables.test.js
Labels: enhancement

#194 Remove debug log line in country ban
  api/hooks/countryBan/index.js
Labels: chore

#195 Sort the custom commands
  views/sdtdServer/partials/settings/commandSettings.ejs
  views/sdtdServer/partials/settings/editCommandModal.ejs
Labels: enhancement

#197 Migrate CI to Github Actions
  .github/workflows/CI.yml
  .travis.yml
Labels: chore

#204 Add Sentry performance monitoring
  api/hooks/sentry.js
  config/http.js
  package-lock.json
  package.json
Labels: enhancement

#205 Fix error in playerTracking when server is offline or not responding to request correctly
  .github/workflows/CI.yml
  api/helpers/sdtd/get-online-players.js
  api/hooks/playerTracking/index.js
  test/unit/hooks/playerTracking/playerTracking.test.js
Labels: bug

#217 Country not properly updated when players connect to a server
  api/hooks/sdtdLogs/index.js
  test/unit/hooks/sdtdlogs/index.test.js
Labels: bug

#220 Regression in settings page
  api/controllers/SdtdServer/settings.js
  test/integration/controllers/settings.test.js
Labels: bug

#225 Make sure enrichData cannot throw inside the post-job logic
  api/hooks/sdtdLogs/LoggingObject.js
  api/hooks/sdtdLogs/enrichEventData.js
  test/unit/hooks/sdtdlogs/LoggingObject.test.js
Labels: bug

#226 Fix res is undefined
  config/http.js
Labels: bug
