Repository CatalysmsServerManager/7-days-to-die-server-manager, pull requests merged in 2020-10, with the labels that each got.

#322 Make tests use real mysql with migrations
  .github/workflows/CI.yml
  api/hooks/sdtdLogs/index.js
  package.json
  sequelize.config.js
  test/integration/controllers/CommandReply.test.js
  test/integration/controllers/shop.test.js
  test/integration/cron-job/cron.test.js
  test/integration/hooks/sdtdLogs/logProcessor.test.js
  test/lifecycle.test.js
  test/unit/helpers/discord/setRoleFromDiscord.test.js
  test/unit/hooks/cron/cron.test.js
  test/unit/hooks/discordBot/handleRoleUpdate.test.js
  test/unit/hooks/sdtdlogs/index.test.js
Labels: chore

#323 Add getting discord owner ids from env variables
  .env.example
  config/custom.js
Labels: enhancement, hacktoberfest

#326 Make create_tables.js an alias for db:migrate
  create_tables.js
Labels: chore

#329 Fix logging hook not started after adding a server
  api/controllers/SdtdServer/add-server.js
Labels: bug

#330 Always upload test artifacts after CI run
  .github/workflows/CI.yml
  test/unit/hooks/countryBan/countryBan.test.js
Labels: chore

#328 Add DB migrations functionality to Docker image
  .dockerignore
  .env.example
  docker-compose.yml
  package-lock.json
  package.json
  scripts/wait-for-db.js
Labels: enhancement

#331 Fix character encoding in database
  config/datastores.js
  config/models.js
  test/lifecycle.test.js
  test/unit/models/BanEntry.test.js
Labels: bug

#336 Fix faulty error handling in callAdmin command
  api/hooks/sdtdCommands/commandHandler.js
  api/hooks/sdtdCommands/commands/callAdmin.js
  api/hooks/sdtdCommands/commands/claim.js
  api/hooks/sdtdCommands/commands/gimme.js
  api/hooks/sdtdCommands/commands/vote.js
  test/unit/hooks/commands/callAdmin.test.js
Labels: bug

#334 Fix bad ping count checker (yet again)
  api/hooks/highPingKick/index.js
  api/utils.js
  test/unit/hooks/highPingKick/index.test.js
  worker.js
Labels: bug

#339 Log which process to Sentry
  api/hooks/sentry.js
Labels: chore

#340 Explicitly log the npm script that started this process to sentry
  api/hooks/sentry.js
  worker.js
Labels: chore

#337 Add code scanning to CI
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: chore

#313 Fix teleport priority for public vs private teleports with the same name
  api/hooks/sdtdCommands/commands/tele.js
  test/lifecycle.test.js
  test/unit/hooks/commands/tele.test.js
Labels: bug

#338 Fix quality validation when giving items to a player via dashboard
  views/player/partials/giveItemButton.ejs
Labels: bug

#342 Fix highpingkick, add massive more test coverage
  api/hooks/highPingKick/index.js
  test/unit/hooks/highPingKick/index.test.js
Labels: bug

#344 Truncate cronjob notifications that are too long to send to discord
  .eslintignore
  api/hooks/discordNotifications/notifications/cronJob.js
  test/lifecycle.test.js
  test/unit/hooks/discordNotifications/notifications/cronJob.test.js
Labels: bug

#347 Create funding.yml
  .github/funding.yml
Labels: chore

#346 Let server owner know when discord notifications fail
  api/hooks/discordNotifications/DiscordNotification.js
  test/unit/hooks/discordNotifications/DiscordNotification.test.js
  test/unit/hooks/discordNotifications/notifications/cronJob.test.js
  test/unit/hooks/discordNotifications/notifications/playerConnected.test.js
  test/unit/hooks/discordNotifications/notifications/playerDisconnected.test.js
Labels: enhancement

#354 Fix example in cron settings
  views/sdtdServer/partials/settings/cronSettings.ejs
Labels: bug

#358 Fix line endings in Windows
  .gitattributes
  config/env/production.js
Labels: bug

#360 Change example docker-compose to match .env.example for port
  docker-compose.yml
Labels: chore

#351 Fix top Discord command validation of argument
  api/hooks/discordBot/commands/sdtd/top.js
Labels: bug

#362 Remove rand-token
  package-lock.json
  package.json
Labels: dependencies

#364 Remove code climate from CI
  .github/workflows/CI.yml
Labels: chore

#366 Remove a bunch of random leftover files
  .jshintrc
  .vscode/settings.json
  lefthook.yml
  package-lock.json
  package.json
  update.sh
Labels: chore

#363 Handle errors better when executing commands via the dashboard
  api/controllers/SdtdServer/execute-command.js
  assets/js/sdtdServer/console.js
  config/routes.js
  package.json
  test/integration/controllers/execute-command.test.js
Labels: bug

#367 Fix issue where null discord user throws TypeError
  api/controllers/User/find-guilds-managed-by-user.js
Labels: bug

#369 Fix codecoverage badge in README
  README.md
Labels: chore

#371 Remove upload test artifact from CI
  .github/workflows/CI.yml
Labels: chore

#376 Create test for the status Discord command
  test/unit/hooks/discordCommands/status.test.js
Labels: chore

#377 Make discord bot errors link to dev discord instead of bot owners
  .env.example
  api/hooks/discordBot/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#359 Use ggs BloodMoonDay to determine next bloodmoon
  api/hooks/discordBot/commands/sdtd/status.js
  test/unit/hooks/discordCommands/status.test.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#332 Add map tile proxy experimental feature
  api/controllers/SdtdServer/server-tile.js
  api/controllers/SdtdServer/set-settings.js
  api/localsfuncs/serverMapUrl.js
  api/models/SdtdConfig.js
  api/view-rendering-fn.js
  assets/js/sdtdServer/map.js
  config/policies.js
  config/routes.js
  config/session.js
  config/views.js
  migrations/20201004001600-add-map-proxy.js
  nodemon.json
  package-lock.json
  package.json
  test/unit/localsfuncs/serverMapUrl.test.js
  views/index.ejs
  views/layouts/applicationLayout.ejs
  views/layouts/defaultLayout.ejs
  views/layouts/homepageLayout.ejs
  views/layouts/homepageLayoutNoFooter.ejs
  views/player/profile.ejs
  views/sdtdServer/chat.ejs
  views/sdtdServer/console.ejs
  views/sdtdServer/dashboard.ejs
  views/sdtdServer/info.ejs
  views/sdtdServer/partials/map.ejs
  views/sdtdServer/partials/serverControl.ejs
  views/sdtdServer/partials/settings/commandSettings.ejs
  views/sdtdServer/partials/settings/discordSettings.ejs
  views/sdtdServer/partials/settings/economySettings.ejs
  views/sdtdServer/partials/settings/experiments.ejs
  views/sdtdServer/players.ejs
  views/sdtdServer/settings.ejs
  views/sdtdServer/tracking.ejs
  views/sdtdTicket/partials/ticketComment.ejs
  views/sdtdTicket/ticket.ejs
  views/user/userDashboard.ejs
Labels: enhancement

#370 High ping kick hook should listen to the correct LoggingObject to receive events
  api/controllers/BannedItemList/set-banned-item-status.js
  api/controllers/SdtdServer/update-connection-info.js
  api/helpers/meta/set-server-active.js
  api/helpers/meta/set-server-inactive.js
  api/hooks/bannedItems/index.js
  api/hooks/countryBan/index.js
  api/hooks/customDiscordNotification/index.js
  api/hooks/customHooks/index.js
  api/hooks/discordChatBridge/chatBridgeChannel.js
  api/hooks/discordChatBridge/index.js
  api/hooks/gbl/index.js
  api/hooks/highPingKick/index.js
  api/hooks/playerTracking/index.js
  api/hooks/sdtdCommands/index.js
  api/hooks/sdtdLogs/index.js
  test/lifecycle.test.js
  test/unit/hooks/sdtdlogs/index.test.js
Labels: bug

#383 Add check to verify that a server has been found in manageServer policy
  api/policies/roles/manageServer.js
  package-lock.json
  package.json
  test/unit/policies/manageServer.test.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#385 Add hash to frontend assets to clear browser caches between versions
  api/localsfuncs/hashFile.js
  api/localsfuncs/scriptTag.js
  api/localsfuncs/stylesheetTag.js
  tasks/config/sails-linker.js
  views/layouts/applicationLayout.sejs
  views/layouts/defaultLayout.sejs
  views/layouts/homepageLayout.sejs
  views/layouts/homepageLayoutNoFooter.sejs
Labels: enhancement

#382 Add fallback for undefined player country in Discord chatbridge rich connected messages
  api/hooks/discordChatBridge/chatBridgeChannel.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#381 Fix loggingHook initializing servers that are set to inactive
  api/hooks/sdtdLogs/index.js
  test/unit/hooks/sdtdlogs/index.test.js
Labels: bug

#387 Replace map proxy tile with real filename so nginx security doesn't think its a dot file
  api/localsfuncs/serverMapUrl.js
  config/routes.js
  config/session.js
  test/unit/localsfuncs/serverMapUrl.test.js
Labels: bug

#390 remove default CSMM admins
  .env.example
Labels: chore, hacktoberfest, hacktoberfest-accepted

#378 Fix issue when trying to give items with spaces in the name via player profile page
  api/controllers/Player/give-item.js
  test/integration/controllers/give-item.test.js
Labels: bug, hacktoberfest-accepted

#401 Minor changes to README
  README.md
Labels: chore

#402 Add check-run-reporter
  .github/workflows/CI.yml
  .gitignore
  package-lock.json
  package.json
Labels: chore

#404 Fix custom command edit button rendering out of order
  views/sdtdServer/partials/settings/commandSettings.sejs
Labels: bug

#405 Fix edit button for custom commands again
  views/sdtdServer/partials/settings/commandSettings.sejs
Labels: bug

#406 Allow check-run-reporter to run on forked repos
  .github/workflows/CI.yml
Labels: chore

#408 Updated cron job 'Test' button to read 'Run now' for functional clarity
  views/sdtdServer/partials/settings/cronSettings.sejs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#397 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore, hacktoberfest-accepted

#392 Refactor Discord notifications to run as Bull jobs
  api/helpers/discord/discordRequest.js
  api/helpers/discord/send-dm.js
  api/helpers/discord/send-message.js
  api/helpers/discord/send-notification.js
  api/hooks/bullboard.js
  api/hooks/discordBot/util/createEmbed.js
  api/hooks/discordNotifications/index.js
  package.json
  test/lifecycle.test.js
  test/unit/helpers/discord/send-message.js
  test/unit/helpers/discord/setRoleFromDiscord.test.js
  test/unit/hooks/discordNotifications/DiscordNotification.test.js
  test/unit/hooks/discordNotifications/notifications/cronJob.test.js
  test/unit/hooks/discordNotifications/notifications/gblMaxBan.test.js
  test/unit/hooks/discordNotifications/notifications/playerConnected.test.js
  test/unit/hooks/discordNotifications/notifications/playerDisconnected.test.js
  worker/processors/README.md
  worker/processors/discordNotification/DiscordNotification.js
  worker/processors/discordNotification/index.js
  worker/processors/discordNotification/notifications/connected.js
  worker/processors/discordNotification/notifications/connectionLost.js
  worker/processors/discordNotification/notifications/countrybanKick.js
  worker/processors/discordNotification/notifications/cronJob.js
  worker/processors/discordNotification/notifications/gblMaxBans.js
  worker/processors/discordNotification/notifications/index.js
  worker/processors/discordNotification/notifications/playerConnected.js
  worker/processors/discordNotification/notifications/playerDisconnected.js
  worker/processors/discordNotification/notifications/systemBoot.js
  worker/processors/discordNotification/notifications/ticket.js
  worker/processors/logs.js
  worker/worker.js
Labels: enhancement

#410 Move bannedItems hook to worker process
  api/controllers/BannedItemList/set-banned-item-status.js
  api/helpers/meta/set-server-inactive.js
  api/hooks/bannedItems/index.js
  api/hooks/bullboard.js
  api/hooks/playerTracking/index.js
  test/unit/hooks/bannedItems/bannedItems.test.js
  test/unit/hooks/playerTracking/playerTracking.test.js
  worker/processors/bannedItems/handleTrackingUpdate.js
  worker/processors/bannedItems/index.js
  worker/worker.js
Labels: enhancement

#414 Move player tracking hook to worker
  api/helpers/meta/set-server-active.js
  api/helpers/redis/publish.js
  api/helpers/redis/subscribe.js
  api/hooks/bannedItems/index.js
  api/hooks/bullboard.js
  api/hooks/economy/objects/killEarner.js
  api/hooks/playerTracking/index.js
  api/hooks/sdtdLogs/index.js
  test/unit/helpers/redis/pubsub.test.js
  test/unit/hooks/playerTracking/playerTracking.test.js
  worker/processors/playerTracking/index.js
  worker/processors/playerTracking/trackingFunctions/basic.js
  worker/processors/playerTracking/trackingFunctions/index.js
  worker/processors/playerTracking/trackingFunctions/inventory.js
  worker/processors/playerTracking/trackingFunctions/location.js
  worker/worker.js
Labels: enhancement

#415 Add default options for how many Bull jobs are kept in history
  api/helpers/get-queue-object.js
  api/hooks/sdtdLogs/LoggingObject.js
Labels: enhancement

#416 Refactor economy killEarner to bull queues instead of redis pubsub
  api/helpers/redis/publish.js
  api/helpers/redis/subscribe.js
  api/hooks/bullboard.js
  api/hooks/economy/objects/killEarner.js
  test/unit/helpers/redis/pubsub.test.js
  test/unit/hooks/playerTracking/playerTracking.test.js
  worker/processors/kill/index.js
  worker/processors/playerTracking/trackingFunctions/basic.js
  worker/worker.js
Labels: bug

#420 Log worker errors to sentry + make sure processors throw
  worker/processors/discordNotification/DiscordNotification.js
  worker/processors/playerTracking/index.js
  worker/worker.js
Labels: enhancement

#421 Delete obsolete call to start bannedItems that caused setting server to active to fail
  api/helpers/meta/set-server-active.js
Labels: bug

#424 Add error logging when giving via claim #412
  api/hooks/sdtdCommands/commands/claim.js
Labels: chore, hacktoberfest-accepted

#425 Add index to usageStats table
  migrations/20201021213935-add-index-to-usagestats.js
Labels: enhancement

#426 Reuse a single connection in redis helpers instead of requesting a new one for every operation
  api/helpers/redis/del.js
  api/helpers/redis/get.js
  api/helpers/redis/incr.js
  api/helpers/redis/set.js
  api/hooks/redis.js
  package-lock.json
  package.json
  test/unit/helpers/redis/del.test.js
  test/unit/helpers/redis/get.test.js
  test/unit/helpers/redis/incr.test.js
  test/unit/helpers/redis/set.test.js
  test/unit/hooks/sdtdlogs/LoggingObject.test.js
Labels: bug

#427 Create dedicated healthcheck endpoint
  api/controllers/etc/health.js
  config/routes.js
  scripts/healthcheck.js
Labels: enhancement

#428 Reuse Bull Queue objects instead of creating new objects
  api/helpers/get-queue-object.js
Labels: bug

#430 Skip sending errors to Sentry about the logging hook
  worker/worker.js
Labels: chore

#396 Implement the option to set the country blacklist to a country whitelist
  api/controllers/SdtdServer/set-settings.js
  api/hooks/countryBan/index.js
  api/models/SdtdConfig.js
  migrations/20201017190502-add-country-ban-whitelist.js
  test/lifecycle.test.js
  test/unit/hooks/countryBan/countryBan.test.js
  views/sdtdServer/partials/settings/countryBanSettings.sejs
Labels: enhancement, hacktoberfest-accepted

#432 Fix chat command errors not being recorded to sentry/logs
  api/hooks/sdtdCommands/commandHandler.js
Labels: bug

#437 Increase performance for economy killEarner by parallelising promises
  worker/processors/kill/index.js
Labels: enhancement, hacktoberfest-accepted

#442 Improve nodemon dev flow by including the worker
  nodemon.json
  package.json
Labels: chore

#443 Increase concurrency for tracking processor
  worker/worker.js
Labels: bug

#445 Allow longer strings than 255 characters for gimme values
  migrations/20201027092742-extend-gimme-value-length.js
Labels: bug

#444 Add lint staged
  package-lock.json
  package.json
Labels: chore, hacktoberfest-accepted
