Repository CatalysmsServerManager/7-days-to-die-server-manager, pull requests merged in 2021-12, with the labels that each got.

#954 A20
  api/controllers/CustomCommand/get-allowed-commands.js
  api/controllers/Player/ban.js
  api/controllers/Player/give-item.js
  api/controllers/Player/kick.js
  api/controllers/Player/teleport.js
  api/controllers/Player/unban.js
  api/controllers/SdtdServer/available-items.js
  api/controllers/SdtdServer/is-online.js
  api/controllers/SdtdServer/restart-server.js
  api/controllers/SdtdServer/send-message.js
  api/helpers/load-sdtdServer-info.js
  api/helpers/sdtd/check-if-available.js
  api/helpers/sdtd/get-allowed-commands.js
  api/helpers/sdtd/load-bans.js
  api/helpers/sdtd/load-player-data.js
  api/helpers/user/get-servers-with-permission.js
  api/hooks/countryBan/index.js
  api/hooks/discordBot/commands/sdtd/execCommand.js
  api/hooks/discordChatBridge/chatBridgeChannel.js
  api/hooks/gbl/index.js
  api/hooks/highPingKick/index.js
  config/customLog.js
  package-lock.json
  package.json
  test/integration/controllers/give-item.test.js
  test/unit/hooks/commands/reply.test.js
  test/unit/hooks/countryBan/countryBan.test.js
  test/unit/hooks/sdtdlogs/handleLogLine.test.js
  worker/processors/logs/handleLogLine.js
  worker/processors/sdtdCommands/commands/claim.js
  worker/processors/sdtdCommands/commands/gimme.js
  worker/processors/sdtdCommands/commands/shop.js
  worker/processors/sdtdCommands/sendReply.js
Labels: enhancement

#960 chore: add tests for A20 CPM log lines
  test/unit/hooks/sdtdlogs/handleLogLine.test.js
  worker/processors/logs/handleLogLine.js
Labels: chore

#961 chore: address all faker deprecation warnings
  test/integration/gbl/gbl-delete.test.js
  test/integration/gbl/get-total-bans.test.js
  test/integration/gbl/search-steamid.test.js
  test/integration/player-teleport/playerTeleport.test.js
  test/integration/roles/update-role.test.js
  test/lifecycle.test.js
  test/unit/helpers/roles/check-permission.test.js
  test/unit/helpers/sdtd/execute-custom-command.test.js
Labels: chore

#969 fix: tele command should use entityId
  worker/processors/sdtdCommands/commands/tele.js
Labels: bug

#970 fix: sending chat messages from dashboard
  api/controllers/SdtdServer/send-message.js
Labels: bug

#971 chore: add detected logs to job data, so error tracking is easier
  test/integration/hooks/sdtdLogs/logProcessor.test.js
  test/unit/hooks/sdtdlogs/processor.test.js
  worker/processors/logs/logProcessor.js
Labels: chore

#973 fix: metadata for log line of lastDeathLocation
  api/hooks/sdtdLogs/enrichers/playerDied.js
Labels: bug

#974 fix: handling of player disconnect logs with bad data
  test/unit/hooks/sdtdlogs/handleLogLine.test.js
  worker/processors/logs/handleLogLine.js
Labels: bug

#975 fix: partial loading of players on server
  api/helpers/sdtd/load-player-data.js
Labels: bug

#977 fix: loading of dashboard for offline servers
  api/controllers/SdtdServer/dashboard.js
Labels: bug

#981 fix: chat message time display inconsistency
  assets/js/sdtdServer/chat.js
Labels: bug

#983 Chat Bridge say2 implementation - v2
  api/controllers/SdtdServer/set-settings.js
  api/hooks/discordChatBridge/chatBridgeChannel.js
  api/models/SdtdConfig.js
  migrations/20211208204811-discord-prefix-suffix-impl.js
  views/sdtdServer/partials/settings/discordSettings.sejs
Labels: enhancement

#987 fix: for when blocked prefixes contains an empty string
  api/hooks/discordChatBridge/chatBridgeChannel.js
Labels: bug

#988 fix(discordNotification): select name field from player role
  worker/processors/discordNotification/notifications/playerConnected.js
  worker/processors/discordNotification/notifications/playerDisconnected.js
Labels: bug

#990 fix(logger): add more checks before handling metadata
  config/customLog.js
Labels: bug

#991 ci(docker): run Docker build for PRs
  .github/workflows/docker.yml
Labels: chore

#993 Default to SSE for 7D2D event detection
  api/hooks/sdtdLogs/index.js
Labels: chore

#995 ci(docker): remove Snyk
  .github/workflows/docker.yml
Labels: chore

#999 fix: Discord error handling when gameserver is offline
  api/hooks/discordBot/commands/sdtd/listServers.js
  api/hooks/discordBot/commands/sdtd/serverInfo.js
  api/hooks/discordBot/commands/sdtd/status.js
  test/unit/hooks/discordCommands/serverInfo.test.js
Labels: bug

#1003 fix: ban button to use steam ID again
  api/controllers/Player/ban.js
  api/controllers/Player/unban.js
  package-lock.json
  test/integration/player/unban.test.js
Labels: bug

#1005 TypeError: Request path contains unescaped characters
  api/hooks/sdtdLogs/eventDetectors/7d2dSSE.js
Labels: bug

#1008 fix: update version of 7d2d API wrapper to handle request timeouts better
  package-lock.json
  package.json
Labels: bug

#1009 fix: handle caching of Discord roles better when adding a new server
  api/controllers/SdtdServer/add-server.js
  api/helpers/meta/get-donator-status.js
  test/unit/donorCheck.test.js
Labels: bug

#1012 fix: issues when setting or removing a player role
  api/controllers/SdtdServer/set-settings.js
  api/controllers/role/add-player.js
  api/controllers/role/remove-player.js
  api/helpers/roles/get-user-role.js
  api/helpers/sdtd/get-player-role.js
  config/policies.js
  test/integration/admin/import-export.test.js
  test/integration/controllers/BannedItemList.test.js
  test/integration/controllers/CommandReply.test.js
  test/integration/controllers/available-items.test.js
  test/integration/controllers/cron/cron-import.test.js
  test/integration/controllers/execute-command.test.js
  test/integration/controllers/give-item.test.js
  test/integration/controllers/player/export.test.js
  test/integration/controllers/savedTeleports.test.js
  test/integration/controllers/set-inventory-tracking.test.js
  test/integration/controllers/set-settings.test.js
  test/integration/controllers/setChatChannel.test.js
  test/integration/controllers/settings.test.js
  test/integration/controllers/shop.test.js
  test/integration/cron-job/cron.test.js
  test/integration/customCommand/createCustomCommand.test.js
  test/integration/customCommand/updateCustomCommand.test.js
  test/integration/etc/stats.test.js
  test/integration/gbl/gbl-delete.test.js
  test/integration/gbl/get-total-bans.test.js
  test/integration/gbl/search-steamid.test.js
  test/integration/player-teleport/playerTeleport.test.js
  test/integration/player/unban.test.js
  test/integration/roles/add-player.test.js
  test/integration/roles/remove-player.test.js
  test/integration/roles/update-role.test.js
  test/lifecycle.test.js
  test/unit/helpers/roles/check-permission.test.js
Labels: bug
