Repository CatalysmsServerManager/7-days-to-die-server-manager, pull requests merged in 2022-09, with the labels that each got.

#1293 fix: soft-delete servers that fail donor check
  api/helpers/user/get-servers-with-permission.js
  api/hooks/historicalInfo/index.js
  api/hooks/sdtdLogs/index.js
  api/middleware/serverDisabledMiddleware.js
  api/models/SdtdServer.js
  config/http.js
  migrations/20220902204824-server-disabled.js
  test/unit/middleware/serverDisabledMiddleware.js
  worker/processors/system/donorCheck.js
Labels: bug

#1295 Make queue concurrency configurable
  worker/worker.js
Labels: chore

#1297 Set disabled status when fetching donor status
  api/controllers/SdtdServer/check-donator.js
Labels: bug

#1299 fix: typo in concurrency + ensure first param is always a number
  worker/worker.js
Labels: bug

#1302 Upgrade to Discord.js 14
  .github/workflows/CI.yml
  .github/workflows/DB-migrations.yml
  Dockerfile
  api/controllers/SdtdServer/discordBot/find-writeable-channels-in-guild.js
  api/controllers/SdtdServer/discordBot/set-chat-channel.js
  api/controllers/SdtdServer/discordBot/set-prefix.js
  api/controllers/User/find-guilds-managed-by-user.js
  api/helpers/discord/get-client.js
  api/helpers/discord/send-message.js
  api/hooks/discordBot/commands/execCommand.js
  api/hooks/discordBot/commands/index.js
  api/hooks/discordBot/commands/listServers.js
  api/hooks/discordBot/commands/lookup.js
  api/hooks/discordBot/commands/meta/restart.js
  api/hooks/discordBot/commands/meta/stats.js
  api/hooks/discordBot/commands/player.js
  api/hooks/discordBot/commands/sdtd/execCommand.js
  api/hooks/discordBot/commands/sdtd/listServers.js
  api/hooks/discordBot/commands/sdtd/lookup.js
  api/hooks/discordBot/commands/sdtd/player.js
  api/hooks/discordBot/commands/sdtd/serverInfo.js
  api/hooks/discordBot/commands/sdtd/status.js
  api/hooks/discordBot/commands/sdtd/top.js
  api/hooks/discordBot/commands/status.js
  api/hooks/discordBot/commands/top.js
  api/hooks/discordBot/index.js
  api/hooks/discordBot/util/createEmbed.js
  api/hooks/discordBot/util/findSdtdServer.js
  api/hooks/discordBot/util/getInteractionOption.js
  api/hooks/discordChatBridge/chatBridgeChannel.js
  api/hooks/economy/objects/discordMessageHandler.js
  api/models/SdtdConfig.js
  config/routes.js
  migrations/20220908174803-discord-upgrade.js
  package-lock.json
  package.json
  test/unit/helpers/discord/send-message.test.js
  test/unit/hooks/customDiscordNotification/discordNotif.test.js
  test/unit/hooks/discordCommands/serverInfo.test.js
  test/unit/hooks/discordCommands/status.test.js
  test/unit/hooks/discordNotifications/DiscordNotification.test.js
  test/unit/hooks/discordNotifications/notifications/cronJob.test.js
  test/unit/hooks/discordNotifications/notifications/gblMaxBan.test.js
  test/unit/hooks/discordNotifications/notifications/playerConnected.test.js
  test/unit/hooks/discordNotifications/notifications/playerDisconnected.test.js
  views/sdtdServer/partials/settings/discordSettings.sejs
  worker/processors/customNotifications/index.js
  worker/processors/discordNotification/DiscordNotification.js
  worker/processors/discordNotification/notifications/SSEThrottled.js
  worker/processors/discordNotification/notifications/connected.js
  worker/processors/discordNotification/notifications/connectionLost.js
  worker/processors/discordNotification/notifications/countrybanKick.js
  worker/processors/discordNotification/notifications/cronJob.js
  worker/processors/discordNotification/notifications/gblMaxBans.js
  worker/processors/discordNotification/notifications/index.js
  worker/processors/discordNotification/notifications/playerConnected.js
  worker/processors/discordNotification/notifications/playerDisconnected.js
  worker/processors/discordNotification/notifications/systemBoot.js
  worker/processors/discordNotification/notifications/ticket.js
Labels: chore

#1306 Add dev docs to README
  README.md
Labels: chore

#1314 Fix: Discord status command needs the he dependency
  api/hooks/discordBot/commands/status.js
Labels: bug

#1316 fix: add a workaround when steam auth servers are not behaving
  api/controllers/AuthController.js
Labels: bug

#1318 fix: revert sentry upgrade
  package-lock.json
  package.json
Labels: bug

#1320 fix: usage of send-message helper when no input embed is given
  api/helpers/discord/send-message.js
Labels: bug

#1323 Allow restarting CSMM via Discord by owners set in env file
  api/helpers/discord/get-client.js
  api/hooks/discordBot/index.js
  api/hooks/discordBot/util/adminRestart.js
Labels: enhancement

#1322 Add more aliases to tp
  worker/processors/sdtdCommands/commands/listTele.js
  worker/processors/sdtdCommands/commands/removetele.js
  worker/processors/sdtdCommands/commands/renameTele.js
  worker/processors/sdtdCommands/commands/setTele.js
  worker/processors/sdtdCommands/commands/telePublic.js
  worker/processors/sdtdCommands/commands/teleprivate.js
Labels: enhancement

#1324 Send a message if a command fails to execute
  api/hooks/discordBot/index.js
Labels: bug

#1326 Fix permission flag bit when checking owned servers
  api/controllers/User/find-guilds-managed-by-user.js
Labels: bug

#1327 Fix how we access Discordjs caches
  api/controllers/SdtdServer/discordBot/get-server-roles.js
  api/hooks/discordBot/roles/handleRoleUpdate.js
  test/unit/hooks/discordBot/handleRoleUpdate.test.js
Labels: bug

#1329 Fix timeout of slash command reply if API requests to gameserver take too long
  api/hooks/discordBot/commands/execCommand.js
  api/hooks/discordBot/commands/listServers.js
  api/hooks/discordBot/commands/lookup.js
  api/hooks/discordBot/commands/player.js
  api/hooks/discordBot/commands/status.js
  api/hooks/discordBot/commands/top.js
  api/hooks/discordBot/index.js
Labels: bug

#1331 Do not try to load writeable Discord channels if no guild is configured
  api/controllers/SdtdServer/discordBot/find-writeable-channels-in-guild.js
Labels: bug

#1338 feat: auto-detect player objects via XBL id in hooks
  api/hooks/sdtdLogs/enrichers/player.js
  test/unit/hooks/sdtdlogs/enrichEventData.test.js
Labels: enhancement
